//
//  Calculation.hpp
//  Numerical Analysis
//
//  Created by 于京平 on 16/7/22.
//  Copyright © 2016年 于京平. All rights reserved.
//

#ifndef Calculation_hpp
#define Calculation_hpp

#include <stdio.h>
#include <iostream>
#include <cstring>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <vector>

using namespace std;

class CalculationResult
{
    private :
    
    double result; // Stores the result generated by the calculating process
    bool isValid; // Whether the result is valid or not.
    string statusInformation; // The text information of the result. It indicates how the result is generated.
    
    public :
    
    //Constructors
    CalculationResult ();
    CalculationResult (double, bool, string);
    
    void SetAllParams (double, bool, string);
    
    // It is not recommened to set the params individually. Unless you are very sure about what you are doing.
    void SetResult (double);
    void SetValidity (bool);
    void SetInformation (string);
    
    double GetResult ();
    bool GetValidity ();
    string GetInformation ();
    
    //Debugging Functions
    void OutputResult ();
};
#endif /* Calculation_hpp */
